In [1]:

import pandas as pd
data_dir = './data/ml-100k/'
data = pd.read_csv(data_dir+'u.data',sep='\t',names=['user_id','items_id','rating',
                                              'time_stamp'])

print(data.head())

   user_id  items_id  rating  time_stamp
0      196       242       3   881250949
1      186       302       3   891717742
2       22       377       1   878887116
3      244        51       2   880606923
4      166       346       1   886397596

In [3]:
# data.groupby(by='user_id').count()

         items_id  rating  time_stamp
user_id
1             272     272         272
2              62      62          62
3              54      54          54
4              24      24          24
5             175     175         175
6             211     211         211
7             403     403         403
8              59      59          59
9              22      22          22
10            184     184         184
11            181     181         181
12             51      51          51
13            636     636         636
14             98      98          98
15            104     104         104
16            140     140         140
17             28      28          28
18            277     277         277
19             20      20          20
20             48      48          48
21            179     179         179
22            128     128         128
23            151     151         151
24             68      68          68
25             78      78          78
26            107     107         107
27             25      25          25
28             79      79          79
29             34      34          34
30             43      43          43
...           ...     ...         ...
914            23      23          23
915            26      26          26
916           317     317         317
917            35      35          35
918           103     103         103
919           217     217         217
920            26      26          26
921           110     110         110
922           127     127         127
923            74      74          74
924            82      82          82
925            32      32          32
926            20      20          20
927           120     120         120
928            32      32          32
929            49      49          49
930            63      63          63
931            61      61          61
932           241     241         241
933           184     184         184
934           174     174         174
935            39      39          39
936           142     142         142
937            40      40          40
938           108     108         108
939            49      49          49
940           107     107         107
941            22      22          22
942            79      79          79
943           168     168         168

[943 rows x 3 columns]

In [6]:
data.nunique()

user_id         943
items_id       1682
rating            5
time_stamp    49282
dtype: int64

In [7]:
users,items = data['user_id'],data['items_id']

In [10]:
users.describe()

count    100000.00000
mean        462.48475
std         266.61442
min           1.00000
25%         254.00000
50%         447.00000
75%         682.00000
max         943.00000
Name: user_id, dtype: float64

In [12]:
items.describe()

count    100000.000000
mean        425.530130
std         330.798356
min           1.000000
25%         175.000000
50%         322.000000
75%         631.000000
max        1682.000000
Name: items_id, dtype: float64

In [13]:
print(users[0],' ',items[0])

196   242